import os
import json
import pandas as pd
from data_pipeline.cleaning.lok_sabha_cleaner import LokSabhaCleaner
from data_pipeline.cleaning.rajya_sabha_cleaner import RajyaSabhaCleaner

def generate_quality_reports(ls_metrics, rs_metrics):
    reports_dir = os.path.join("data", "reports")
    os.makedirs(reports_dir, exist_ok=True)
    
    ls_report_path = os.path.join(reports_dir, "lok_sabha_quality_report.json")
    with open(ls_report_path, "w", encoding="utf-8") as f:
        json.dump(ls_metrics, f, indent=2)
        
    rs_report_path = os.path.join(reports_dir, "rajya_sabha_quality_report.json")
    with open(rs_report_path, "w", encoding="utf-8") as f:
        json.dump(rs_metrics, f, indent=2)
        
    # Generate Combined Quality Comparison Markdown Matrix
    md_content = """# MPLADS Data Quality & Data Cleaning Report

## Executive Summary
This report presents empirical data quality metrics generated by running the isolated **Data Cleaning Layer** across both **Lok Sabha** and **Rajya Sabha** raw datasets.

---

## Data Quality Comparison Matrix

| Metric | Lok Sabha (LOK_SABHA) | Rajya Sabha (RAJYA_SABHA) | Combined Total |
| :--- | :---: | :---: | :---: |
"""
    
    ls_total_raw = sum(m["raw_rows"] for m in ls_metrics)
    ls_total_clean = sum(m["clean_rows"] for m in ls_metrics)
    ls_blank_rows = sum(m["blank_rows_removed"] for m in ls_metrics)
    ls_footers = sum(m["footer_rows_stripped"] for m in ls_metrics)
    ls_repeated = sum(m["repeated_headers_removed"] for m in ls_metrics)
    ls_quarantine = sum(m["quarantined_rows"] for m in ls_metrics)
    
    rs_total_raw = sum(m["raw_rows"] for m in rs_metrics)
    rs_total_clean = sum(m["clean_rows"] for m in rs_metrics)
    rs_blank_rows = sum(m["blank_rows_removed"] for m in rs_metrics)
    rs_footers = sum(m["footer_rows_stripped"] for m in rs_metrics)
    rs_repeated = sum(m["repeated_headers_removed"] for m in rs_metrics)
    rs_quarantine = sum(m["quarantined_rows"] for m in rs_metrics)

    md_content += f"| **Total Raw Rows** | {ls_total_raw:,} | {rs_total_raw:,} | {ls_total_raw + rs_total_raw:,} |
"
    md_content += f"| **Clean Valid Rows** | {ls_total_clean:,} | {rs_total_clean:,} | {ls_total_clean + rs_total_clean:,} |
"
    md_content += f"| **Blank Rows Removed** | {ls_blank_rows} | {rs_blank_rows} | {ls_blank_rows + rs_blank_rows} |
"
    md_content += f"| **Grand Total Footers Stripped** | {ls_footers} | {rs_footers} | {ls_footers + rs_footers} |
"
    md_content += f"| **Repeated Headers Stripped** | {ls_repeated} | {rs_repeated} | {ls_repeated + rs_repeated} |
"
    md_content += f"| **Quarantined Malformed Rows** | {ls_quarantine} | {rs_quarantine} | {ls_quarantine + rs_quarantine} |

"
    md_content += f"| **Total Raw Rows** | {ls_total_raw:,} | {rs_total_raw:,} | {ls_total_raw + rs_total_raw:,} |\n"
    md_content += f"| **Clean Valid Rows** | {ls_total_clean:,} | {rs_total_clean:,} | {ls_total_clean + rs_total_clean:,} |\n"
    md_content += f"| **Blank Rows Removed** | {ls_blank_rows} | {rs_blank_rows} | {ls_blank_rows + rs_blank_rows} |\n"
    md_content += f"| **Grand Total Footers Stripped** | {ls_footers} | {rs_footers} | {ls_footers + rs_footers} |\n"
    md_content += f"| **Repeated Headers Stripped** | {ls_repeated} | {rs_repeated} | {ls_repeated + rs_repeated} |\n"
    md_content += f"| **Quarantined Malformed Rows** | {ls_quarantine} | {rs_quarantine} | {ls_quarantine + rs_quarantine} |\n\n"
    
    md_content += "## Dataset Breakdown

"
    md_content += "### Lok Sabha Datasets

"
    md_content += "| Dataset Type | Raw Rows | Clean Rows | Blank Removed | Footers Stripped | Quarantined |
"
    md_content += "| :--- | :---: | :---: | :---: | :---: | :---: |
"
    md_content += "## Dataset Breakdown\n\n"
    md_content += "### Lok Sabha Datasets\n\n"
    md_content += "| Dataset Type | Raw Rows | Clean Rows | Blank Removed | Footers Stripped | Quarantined |\n"
    md_content += "| :--- | :---: | :---: | :---: | :---: | :---: |\n"
    for m in ls_metrics:
        md_content += f"| {m['dataset']} | {m['raw_rows']:,} | {m['clean_rows']:,} | {m['blank_rows_removed']} | {m['footer_rows_stripped']} | {m['quarantined_rows']} |
"
        md_content += f"| `{m['dataset']}` | {m['raw_rows']:,} | {m['clean_rows']:,} | {m['blank_rows_removed']} | {m['footer_rows_stripped']} | {m['quarantined_rows']} |\n"
        
    md_content += "
### Rajya Sabha Datasets

"
    md_content += "| Dataset Type | Raw Rows | Clean Rows | Blank Removed | Footers Stripped | Quarantined |
"
    md_content += "| :--- | :---: | :---: | :---: | :---: | :---: |
"
    md_content += "\n### Rajya Sabha Datasets\n\n"
    md_content += "| Dataset Type | Raw Rows | Clean Rows | Blank Removed | Footers Stripped | Quarantined |\n"
    md_content += "| :--- | :---: | :---: | :---: | :---: | :---: |\n"
    for m in rs_metrics:
        md_content += f"| {m['dataset']} | {m['raw_rows']:,} | {m['clean_rows']:,} | {m['blank_rows_removed']} | {m['footer_rows_stripped']} | {m['quarantined_rows']} |
"
        md_content += f"| `{m['dataset']}` | {m['raw_rows']:,} | {m['clean_rows']:,} | {m['blank_rows_removed']} | {m['footer_rows_stripped']} | {m['quarantined_rows']} |\n"

    comp_path = os.path.join(reports_dir, "combined_quality_comparison.md")
    with open(comp_path, "w", encoding="utf-8") as f:
        f.write(md_content)
        
    print(f"Data Quality Reports successfully generated in {reports_dir}")

def run_pipeline():
    base_data_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "data"))
    
    ls_raw = os.path.join(base_data_dir, "LS_DATASET")
    ls_clean = os.path.join(base_data_dir, "cleaned", "lok_sabha")
    ls_quarant = os.path.join(base_data_dir, "quarantine", "lok_sabha")
    
    rs_raw = os.path.join(base_data_dir, "RS_DATASET")
    rs_clean = os.path.join(base_data_dir, "cleaned", "rajya_sabha")
    rs_quarant = os.path.join(base_data_dir, "quarantine", "rajya_sabha")
    
    ls_cleaner = LokSabhaCleaner(ls_raw, ls_clean, ls_quarant)
    ls_metrics = ls_cleaner.clean_all()
    
    rs_cleaner = RajyaSabhaCleaner(rs_raw, rs_clean, rs_quarant)
    rs_metrics = rs_cleaner.clean_all()
    
    generate_quality_reports(ls_metrics, rs_metrics)
    print("
[NIRIKSHAK AI] Data Cleaning Pipeline completed successfully for BOTH Lok Sabha & Rajya Sabha datasets!")
    print("[NIRIKSHAK AI] Data Cleaning Pipeline completed successfully for BOTH Lok Sabha & Rajya Sabha datasets!")

if __name__ == "__main__":
    run_pipeline()
