import os
import json
import pandas as pd
from data_pipeline.cleaning.lok_sabha_cleaner import LokSabhaCleaner
from data_pipeline.cleaning.rajya_sabha_cleaner import RajyaSabhaCleaner

with open("data_pipeline/cleaning/pipeline.py", "w", encoding="utf-8") as out:
    out.write('''import os
import json
import pandas as pd
from data_pipeline.cleaning.lok_sabha_cleaner import LokSabhaCleaner
from data_pipeline.cleaning.rajya_sabha_cleaner import RajyaSabhaCleaner

def generate_quality_reports(ls_metrics, rs_metrics):
    reports_dir = os.path.join("data", "reports")
    os.makedirs(reports_dir, exist_ok=True)
    
    ls_report_path = os.path.join(reports_dir, "lok_sabha_quality_report.json")
    with open(ls_report_path, "w", encoding="utf-8") as f:
        json.dump(ls_metrics, f, indent=2)
        
    rs_report_path = os.path.join(reports_dir, "rajya_sabha_quality_report.json")
    with open(rs_report_path, "w", encoding="utf-8") as f:
        json.dump(rs_metrics, f, indent=2)
        
    # Generate Combined Quality Comparison Markdown Matrix
    md_content = """# MPLADS Data Quality & Data Cleaning Report

## Executive Summary
This report presents empirical data quality metrics generated by running the isolated **Data Cleaning Layer** across both **Lok Sabha** and **Rajya Sabha** raw datasets.

---

## Data Quality Comparison Matrix

| Metric | Lok Sabha (LOK_SABHA) | Rajya Sabha (RAJYA_SABHA) | Combined Total |
| :--- | :---: | :---: | :---: |
"""
    
    ls_total_raw = sum(m["raw_rows"] for m in ls_metrics)
    ls_total_clean = sum(m["clean_rows"] for m in ls_metrics)
    ls_blank_rows = sum(m["blank_rows_removed"] for m in ls_metrics)
    ls_footers = sum(m["footer_rows_stripped"] for m in ls_metrics)
    ls_repeated = sum(m["repeated_headers_removed"] for m in ls_metrics)
    ls_quarantine = sum(m["quarantined_rows"] for m in ls_metrics)
    
    rs_total_raw = sum(m["raw_rows"] for m in rs_metrics)
    rs_total_clean = sum(m["clean_rows"] for m in rs_metrics)
    rs_blank_rows = sum(m["blank_rows_removed"] for m in rs_metrics)
    rs_footers = sum(m["footer_rows_stripped"] for m in rs_metrics)
    rs_repeated = sum(m["repeated_headers_removed"] for m in rs_metrics)
    rs_quarantine = sum(m["quarantined_rows"] for m in rs_metrics)

    md_content += f"| **Total Raw Rows** | {ls_total_raw:,} | {rs_total_raw:,} | {ls_total_raw + rs_total_raw:,} |\n"
    md_content += f"| **Clean Valid Rows** | {ls_total_clean:,} | {rs_total_clean:,} | {ls_total_clean + rs_total_clean:,} |\n"
    md_content += f"| **Blank Rows Removed** | {ls_blank_rows} | {rs_blank_rows} | {ls_blank_rows + rs_blank_rows} |\n"
    md_content += f"| **Grand Total Footers Stripped** | {ls_footers} | {rs_footers} | {ls_footers + rs_footers} |\n"
    md_content += f"| **Repeated Headers Stripped** | {ls_repeated} | {rs_repeated} | {ls_repeated + rs_repeated} |\n"
    md_content += f"| **Quarantined Malformed Rows** | {ls_quarantine} | {rs_quarantine} | {ls_quarantine + rs_quarantine} |\n\n"
    
    md_content += "## Dataset Breakdown\n\n"
    md_content += "### Lok Sabha Datasets\n\n"
    md_content += "| Dataset Type | Raw Rows | Clean Rows | Blank Removed | Footers Stripped | Quarantined |\n"
    md_content += "| :--- | :---: | :---: | :---: | :---: | :---: |\n"
    for m in ls_metrics:
        md_content += f"| {m['dataset']} | {m['raw_rows']:,} | {m['clean_rows']:,} | {m['blank_rows_removed']} | {m['footer_rows_stripped']} | {m['quarantined_rows']} |\n"
        
    md_content += "\n### Rajya Sabha Datasets\n\n"
    md_content += "| Dataset Type | Raw Rows | Clean Rows | Blank Removed | Footers Stripped | Quarantined |\n"
    md_content += "| :--- | :---: | :---: | :---: | :---: | :---: |\n"
    for m in rs_metrics:
        md_content += f"| {m['dataset']} | {m['raw_rows']:,} | {m['clean_rows']:,} | {m['blank_rows_removed']} | {m['footer_rows_stripped']} | {m['quarantined_rows']} |\n"

    comp_path = os.path.join(reports_dir, "combined_quality_comparison.md")
    with open(comp_path, "w", encoding="utf-8") as f:
        f.write(md_content)
        
    print(f"Data Quality Reports successfully generated in {reports_dir}")

def run_pipeline():
    base_data_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "data"))
    
    ls_raw = os.path.join(base_data_dir, "LS_DATASET")
    ls_clean = os.path.join(base_data_dir, "cleaned", "lok_sabha")
    ls_quarant = os.path.join(base_data_dir, "quarantine", "lok_sabha")
    
    rs_raw = os.path.join(base_data_dir, "RS_DATASET")
    rs_clean = os.path.join(base_data_dir, "cleaned", "rajya_sabha")
    rs_quarant = os.path.join(base_data_dir, "quarantine", "rajya_sabha")
    
    ls_cleaner = LokSabhaCleaner(ls_raw, ls_clean, ls_quarant)
    ls_metrics = ls_cleaner.clean_all()
    
    rs_cleaner = RajyaSabhaCleaner(rs_raw, rs_clean, rs_quarant)
    rs_metrics = rs_cleaner.clean_all()
    
    generate_quality_reports(ls_metrics, rs_metrics)
    print("\n[NIRIKSHAK AI] Data Cleaning Pipeline completed successfully for BOTH Lok Sabha & Rajya Sabha datasets!")

if __name__ == "__main__":
    run_pipeline()
''')

with open("tests/test_cleaning.py", "w", encoding="utf-8") as out:
    out.write('''import pytest
import os
import pandas as pd
from data_pipeline.cleaning.whitespace import clean_whitespace
from data_pipeline.cleaning.encoding import clean_encoding
from data_pipeline.cleaning.nulls import clean_null_value
from data_pipeline.cleaning.numeric import clean_numeric_val
from data_pipeline.cleaning.dates import clean_date_val
from data_pipeline.cleaning.metadata import is_grand_total_row, is_repeated_header_row

def test_whitespace_and_encoding():
    assert clean_whitespace("  Ravi Kishan  ") == "Ravi Kishan"
    assert clean_whitespace("Shri  Ravi  Kishan") == "Shri Ravi Kishan"
    assert clean_whitespace("  \t\nAdv  Dean\xa0Kuriakose\n ") == "Adv Dean Kuriakose"

def test_null_value_cleaning():
    assert clean_null_value("N/A") is None
    assert clean_null_value("n/a") is None
    assert clean_null_value("nan") is None
    assert clean_null_value("NULL") is None
    assert clean_null_value("  ") is None
    assert clean_null_value("0") == "0"
    assert clean_null_value("Valid Text") == "Valid Text"

def test_numeric_cleaning():
    val, valid = clean_numeric_val("? 83,18,05,53,325.71")
    assert valid is True
    assert val == 83180553325.71
    
    val_zero, valid_zero = clean_numeric_val("0")
    assert valid_zero is True
    assert val_zero == 0.0

    val_bad, valid_bad = clean_numeric_val("INVALID_AMOUNT_XYZ")
    assert valid_bad is False

def test_date_cleaning():
    d1, valid1 = clean_date_val("08-Jul-2024")
    assert valid1 is True
    assert d1 == "2024-07-08"
    
    d2, valid2 = clean_date_val("2024-04-01")
    assert valid2 is True
    assert d2 == "2024-04-01"

    d_bad, valid_bad = clean_date_val("31/02/2024")
    assert valid_bad is False

def test_metadata_stripping():
    row_gt = pd.Series(["Grand Total", "", "", "83,18,05,53,325.71"])
    assert is_grand_total_row(row_gt) is True
    
    cols = ["Sr. No.", "State", "MP Name", "Amount"]
    row_rep = pd.Series(["Sr. No.", "State", "MP Name", "Amount"])
    assert is_repeated_header_row(row_rep, cols) is True

def test_idempotency():
    val1 = clean_whitespace("  Shri  NK  Premachandran  ")
    val2 = clean_whitespace(val1)
    assert val1 == val2 == "Shri NK Premachandran"
''')

print("Created pipeline.py and test_cleaning.py!")
