import { ConstituencyMPLADS } from './mplads';

// Auto-generated from real MPLADS dataset - all 36 states/UTs
export const MOCK_CONSTITUENCIES: ConstituencyMPLADS[] = [
  {
    id: 'andaman_and_nicobar_islands', name: 'Andaman And Nicobar Islands', state: 'Andaman And Nicobar Islands',
    mpName: 'Multiple MPs', party: '',
    lat: 11.7401, lng: 92.6586,
    sanctionedAmount: 3.6, releasedAmount: 3.1,
    utilizedAmount: 2.2,
    worksRecommended: 15, worksCompleted: 0, worksPending: 15,
    unspentBalanceAgeMonths: 25,
    anomalyFlags: [{ type: 'inflated_billing', severity: 'high' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'andhra_pradesh', name: 'Andhra Pradesh', state: 'Andhra Pradesh',
    mpName: 'Multiple MPs', party: '',
    lat: 15.9129, lng: 79.74,
    sanctionedAmount: 193.5, releasedAmount: 164.5,
    utilizedAmount: 0.2,
    worksRecommended: 2945, worksCompleted: 2523, worksPending: 422,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'arunachal_pradesh', name: 'Arunachal Pradesh', state: 'Arunachal Pradesh',
    mpName: 'Multiple MPs', party: '',
    lat: 28.218, lng: 94.7278,
    sanctionedAmount: 19.2, releasedAmount: 16.3,
    utilizedAmount: 11.5,
    worksRecommended: 244, worksCompleted: 203, worksPending: 41,
    unspentBalanceAgeMonths: 10,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'assam', name: 'Assam', state: 'Assam',
    mpName: 'Multiple MPs', party: '',
    lat: 26.2006, lng: 92.9376,
    sanctionedAmount: 101.2, releasedAmount: 86.0,
    utilizedAmount: 60.7,
    worksRecommended: 1612, worksCompleted: 1411, worksPending: 201,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'bihar', name: 'Bihar', state: 'Bihar',
    mpName: 'Multiple MPs', party: '',
    lat: 25.0961, lng: 85.3131,
    sanctionedAmount: 336.6, releasedAmount: 286.1,
    utilizedAmount: 0.4,
    worksRecommended: 4513, worksCompleted: 3656, worksPending: 857,
    unspentBalanceAgeMonths: 11,
    anomalyFlags: [{ type: 'delayed_utilization', severity: 'medium' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'chandigarh', name: 'Chandigarh', state: 'Chandigarh',
    mpName: 'Multiple MPs', party: '',
    lat: 30.7333, lng: 76.7794,
    sanctionedAmount: 6.6, releasedAmount: 5.6,
    utilizedAmount: 4.0,
    worksRecommended: 96, worksCompleted: 86, worksPending: 10,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'chhattisgarh', name: 'Chhattisgarh', state: 'Chhattisgarh',
    mpName: 'Multiple MPs', party: '',
    lat: 21.2787, lng: 81.8661,
    sanctionedAmount: 104.2, releasedAmount: 88.6,
    utilizedAmount: 0.2,
    worksRecommended: 2118, worksCompleted: 1875, worksPending: 243,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'delhi', name: 'Delhi', state: 'Delhi',
    mpName: 'Multiple MPs', party: '',
    lat: 28.7041, lng: 77.1025,
    sanctionedAmount: 38.9, releasedAmount: 33.1,
    utilizedAmount: 23.3,
    worksRecommended: 472, worksCompleted: 411, worksPending: 61,
    unspentBalanceAgeMonths: 10,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'goa', name: 'Goa', state: 'Goa',
    mpName: 'Multiple MPs', party: '',
    lat: 15.2993, lng: 74.124,
    sanctionedAmount: 7.0, releasedAmount: 6.0,
    utilizedAmount: 4.2,
    worksRecommended: 87, worksCompleted: 68, worksPending: 19,
    unspentBalanceAgeMonths: 10,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'gujarat', name: 'Gujarat', state: 'Gujarat',
    mpName: 'Multiple MPs', party: '',
    lat: 22.2587, lng: 71.1924,
    sanctionedAmount: 216.1, releasedAmount: 183.7,
    utilizedAmount: 0.2,
    worksRecommended: 6372, worksCompleted: 5665, worksPending: 707,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'haryana', name: 'Haryana', state: 'Haryana',
    mpName: 'Multiple MPs', party: '',
    lat: 29.0588, lng: 76.0856,
    sanctionedAmount: 73.6, releasedAmount: 62.6,
    utilizedAmount: 44.2,
    worksRecommended: 1504, worksCompleted: 1333, worksPending: 171,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'himachal_pradesh', name: 'Himachal Pradesh', state: 'Himachal Pradesh',
    mpName: 'Multiple MPs', party: '',
    lat: 31.1048, lng: 77.1734,
    sanctionedAmount: 35.3, releasedAmount: 30.0,
    utilizedAmount: 0.1,
    worksRecommended: 1526, worksCompleted: 1360, worksPending: 166,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'jammu_and_kashmir', name: 'Jammu And Kashmir', state: 'Jammu And Kashmir',
    mpName: 'Multiple MPs', party: '',
    lat: 33.7782, lng: 76.5762,
    sanctionedAmount: 42.3, releasedAmount: 36.0,
    utilizedAmount: 25.4,
    worksRecommended: 870, worksCompleted: 754, worksPending: 116,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'jharkhand', name: 'Jharkhand', state: 'Jharkhand',
    mpName: 'Multiple MPs', party: '',
    lat: 23.6102, lng: 85.2799,
    sanctionedAmount: 122.4, releasedAmount: 104.0,
    utilizedAmount: 1.2,
    worksRecommended: 3575, worksCompleted: 3171, worksPending: 404,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'karnataka', name: 'Karnataka', state: 'Karnataka',
    mpName: 'Multiple MPs', party: '',
    lat: 15.3173, lng: 75.7139,
    sanctionedAmount: 161.2, releasedAmount: 137.0,
    utilizedAmount: 1.3,
    worksRecommended: 2655, worksCompleted: 2350, worksPending: 305,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'kerala', name: 'Kerala', state: 'Kerala',
    mpName: 'Multiple MPs', party: '',
    lat: 10.8505, lng: 76.2711,
    sanctionedAmount: 150.3, releasedAmount: 127.8,
    utilizedAmount: 0.2,
    worksRecommended: 2836, worksCompleted: 2398, worksPending: 438,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'ladakh', name: 'Ladakh', state: 'Ladakh',
    mpName: 'Multiple MPs', party: '',
    lat: 34.1526, lng: 77.577,
    sanctionedAmount: 1.6, releasedAmount: 1.4,
    utilizedAmount: 1.0,
    worksRecommended: 19, worksCompleted: 17, worksPending: 2,
    unspentBalanceAgeMonths: 13,
    anomalyFlags: [{ type: 'delayed_utilization', severity: 'medium' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'lakshadweep', name: 'Lakshadweep', state: 'Lakshadweep',
    mpName: 'Multiple MPs', party: '',
    lat: 10.5667, lng: 72.6417,
    sanctionedAmount: 5.9, releasedAmount: 5.0,
    utilizedAmount: 3.5,
    worksRecommended: 27, worksCompleted: 23, worksPending: 4,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'madhya_pradesh', name: 'Madhya Pradesh', state: 'Madhya Pradesh',
    mpName: 'Multiple MPs', party: '',
    lat: 22.9734, lng: 78.6569,
    sanctionedAmount: 232.0, releasedAmount: 197.2,
    utilizedAmount: 0.3,
    worksRecommended: 5653, worksCompleted: 4890, worksPending: 763,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'maharashtra', name: 'Maharashtra', state: 'Maharashtra',
    mpName: 'Multiple MPs', party: '',
    lat: 19.7515, lng: 75.7139,
    sanctionedAmount: 229.2, releasedAmount: 194.8,
    utilizedAmount: 0.1,
    worksRecommended: 2393, worksCompleted: 1717, worksPending: 676,
    unspentBalanceAgeMonths: 16,
    anomalyFlags: [{ type: 'delayed_utilization', severity: 'medium' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'manipur', name: 'Manipur', state: 'Manipur',
    mpName: 'Multiple MPs', party: '',
    lat: 24.6637, lng: 93.9063,
    sanctionedAmount: 20.5, releasedAmount: 17.4,
    utilizedAmount: 12.3,
    worksRecommended: 77, worksCompleted: 0, worksPending: 77,
    unspentBalanceAgeMonths: 26,
    anomalyFlags: [{ type: 'fund_diversion', severity: 'critical' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'meghalaya', name: 'Meghalaya', state: 'Meghalaya',
    mpName: 'Multiple MPs', party: '',
    lat: 25.467, lng: 91.3662,
    sanctionedAmount: 19.9, releasedAmount: 16.9,
    utilizedAmount: 11.9,
    worksRecommended: 469, worksCompleted: 415, worksPending: 54,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'mizoram', name: 'Mizoram', state: 'Mizoram',
    mpName: 'Multiple MPs', party: '',
    lat: 23.1645, lng: 92.9376,
    sanctionedAmount: 10.0, releasedAmount: 8.5,
    utilizedAmount: 6.0,
    worksRecommended: 172, worksCompleted: 131, worksPending: 41,
    unspentBalanceAgeMonths: 12,
    anomalyFlags: [{ type: 'delayed_utilization', severity: 'medium' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'nagaland', name: 'Nagaland', state: 'Nagaland',
    mpName: 'Multiple MPs', party: '',
    lat: 26.1584, lng: 94.5624,
    sanctionedAmount: 14.6, releasedAmount: 12.4,
    utilizedAmount: 8.8,
    worksRecommended: 56, worksCompleted: 35, worksPending: 21,
    unspentBalanceAgeMonths: 17,
    anomalyFlags: [{ type: 'delayed_utilization', severity: 'medium' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'odisha', name: 'Odisha', state: 'Odisha',
    mpName: 'Multiple MPs', party: '',
    lat: 20.9517, lng: 85.0985,
    sanctionedAmount: 145.4, releasedAmount: 123.6,
    utilizedAmount: 0.2,
    worksRecommended: 4110, worksCompleted: 3676, worksPending: 434,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'puducherry', name: 'Puducherry', state: 'Puducherry',
    mpName: 'Multiple MPs', party: '',
    lat: 11.9416, lng: 79.8083,
    sanctionedAmount: 5.5, releasedAmount: 4.7,
    utilizedAmount: 0.1,
    worksRecommended: 28, worksCompleted: 0, worksPending: 28,
    unspentBalanceAgeMonths: 24,
    anomalyFlags: [{ type: 'inflated_billing', severity: 'high' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'punjab', name: 'Punjab', state: 'Punjab',
    mpName: 'Multiple MPs', party: '',
    lat: 31.1471, lng: 75.3412,
    sanctionedAmount: 111.6, releasedAmount: 94.9,
    utilizedAmount: 1.3,
    worksRecommended: 3567, worksCompleted: 3179, worksPending: 388,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'rajasthan', name: 'Rajasthan', state: 'Rajasthan',
    mpName: 'Multiple MPs', party: '',
    lat: 27.0238, lng: 74.2179,
    sanctionedAmount: 144.9, releasedAmount: 123.2,
    utilizedAmount: 0.1,
    worksRecommended: 2254, worksCompleted: 1899, worksPending: 355,
    unspentBalanceAgeMonths: 7,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'sikkim', name: 'Sikkim', state: 'Sikkim',
    mpName: 'Multiple MPs', party: '',
    lat: 27.533, lng: 88.5122,
    sanctionedAmount: 10.1, releasedAmount: 8.6,
    utilizedAmount: 6.1,
    worksRecommended: 62, worksCompleted: 21, worksPending: 41,
    unspentBalanceAgeMonths: 22,
    anomalyFlags: [{ type: 'inflated_billing', severity: 'high' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'tamil_nadu', name: 'Tamil Nadu', state: 'Tamil Nadu',
    mpName: 'Multiple MPs', party: '',
    lat: 11.1271, lng: 78.6569,
    sanctionedAmount: 325.1, releasedAmount: 276.3,
    utilizedAmount: 0.7,
    worksRecommended: 4060, worksCompleted: 3360, worksPending: 700,
    unspentBalanceAgeMonths: 10,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'telangana', name: 'Telangana', state: 'Telangana',
    mpName: 'Multiple MPs', party: '',
    lat: 18.1124, lng: 79.0193,
    sanctionedAmount: 127.6, releasedAmount: 108.5,
    utilizedAmount: 76.6,
    worksRecommended: 3733, worksCompleted: 3316, worksPending: 417,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'the_dadra_and_nagar_haveli_and_daman_and_diu', name: 'The Dadra And Nagar Haveli And Daman And Diu', state: 'The Dadra And Nagar Haveli And Daman And Diu',
    mpName: 'Multiple MPs', party: '',
    lat: 20.1809, lng: 73.0169,
    sanctionedAmount: 0.1, releasedAmount: 0.1,
    utilizedAmount: 0.1,
    worksRecommended: 2, worksCompleted: 2, worksPending: 0,
    unspentBalanceAgeMonths: 15,
    anomalyFlags: [{ type: 'delayed_utilization', severity: 'medium' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'tripura', name: 'Tripura', state: 'Tripura',
    mpName: 'Multiple MPs', party: '',
    lat: 23.9408, lng: 91.9882,
    sanctionedAmount: 13.7, releasedAmount: 11.6,
    utilizedAmount: 8.2,
    worksRecommended: 53, worksCompleted: 0, worksPending: 53,
    unspentBalanceAgeMonths: 25,
    anomalyFlags: [{ type: 'inflated_billing', severity: 'high' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'uttar_pradesh', name: 'Uttar Pradesh', state: 'Uttar Pradesh',
    mpName: 'Multiple MPs', party: '',
    lat: 26.8467, lng: 80.9462,
    sanctionedAmount: 750.9, releasedAmount: 638.3,
    utilizedAmount: 6.8,
    worksRecommended: 14898, worksCompleted: 12274, worksPending: 2624,
    unspentBalanceAgeMonths: 7,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'uttarakhand', name: 'Uttarakhand', state: 'Uttarakhand',
    mpName: 'Multiple MPs', party: '',
    lat: 30.0668, lng: 79.0193,
    sanctionedAmount: 22.4, releasedAmount: 19.0,
    utilizedAmount: 13.4,
    worksRecommended: 686, worksCompleted: 609, worksPending: 77,
    unspentBalanceAgeMonths: 6,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
  {
    id: 'west_bengal', name: 'West Bengal', state: 'West Bengal',
    mpName: 'Multiple MPs', party: '',
    lat: 22.9868, lng: 87.855,
    sanctionedAmount: 317.4, releasedAmount: 269.8,
    utilizedAmount: 0.1,
    worksRecommended: 4743, worksCompleted: 3928, worksPending: 815,
    unspentBalanceAgeMonths: 7,
    anomalyFlags: [{ type: 'other', severity: 'low' }],
    lastUpdated: 'Sep 2026',
  },
];